openapi: 3.0.3

info:
  title: Eclipse Kapua REST API - Authentication
  version: '1.0'
  contact:
    name: Eclipse Kapua Dev Team
    url: https://eclipse.org/kapua
    email: kapua-dev@eclipse.org
  license:
    name: Eclipse Public License 2.0
    url: https://www.eclipse.org/legal/epl-2.0

paths: { }

components:
  schemas:
    accessToken:
      description: The token of a User session, obtained after a successful login.
      allOf:
        - $ref: '../openapi.yaml#/components/schemas/kapuaUpdatableEntity'
        - type: object
          properties:
            userId:
              $ref: '../openapi.yaml#/components/schemas/kapuaId'
            tokenId:
              $ref: '#/components/schemas/jwt'
            expiresOn:
              type: string
              format: 'date-time'
            invalidatedOn:
              type: string
              format: 'date-time'
            refreshToken:
              type: string
              format: uuid
            refreshExpiresOn:
              type: string
              format: 'date-time'
            trustKey:
              type: string
              description: A long-lived key to be used within an authentication with MFA from a trusted machine
              pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
    ssoData:
      type: object
      description:
        SSO-account data, refers to logged account and populated only when the platform uses a SSO broker
      properties:
        accountSupportsBrokering:
          type: boolean
          description: Whether the logged account supports SSO brokering.
        accountSupportsDirectLogin:
          type: boolean
          description: Whether the logged account supports direct SSO login (without email and 2fa).
        brokeringApiConnectionIssues:
          type: boolean
          description: Whether the openID brokering API is currently unreachable, which may cause SSO login issues.
        uriSuffixDirectLogin:
          type: string
          description:
            The URI query suffix to append when redirecting to the direct login page for this account.
          example: '?accountid=my-account'
        companyDomainNames:
          type: array
          items:
            type: string
          description: the domain names associated to the company of the account
      example:
        accountSupportsBrokering: true
        accountSupportsDirectLogin: true
        brokeringApiConnectionIssues: false
        uriSuffixDirectLogin: '?accountid=my-account-name'
        companyDomainNames:
          - 'company.com'
          - 'company.org'
          - 'anothercompanydomain.net'
    loginInfo:
      type: object
      properties:
        accessToken:
          $ref: '#/components/schemas/accessToken'
        accessPermissions:
          description: The list of Permission directly to the User
          type: array
          items:
            $ref: '../accessInfo/accessInfo.yaml#/components/schemas/accessPermission'
        rolePermissions:
          description: The list of Permission assigned to the User via Roles
          type: array
          items:
            $ref: '../role/role.yaml#/components/schemas/rolePermission'
        groupPermissions:
          description: The list of Permission assigned to the User via UserGroups
          type: array
          items:
            $ref: '../group/group.yaml#/components/schemas/groupPermission'
        groupRolePermissions:
          description: The list of Permission assigned to the User via Roles assigned to UserGroups
          type: array
          items:
            $ref: '../role/role.yaml#/components/schemas/rolePermission'
#        ssoData:
#          $ref: '#/components/schemas/ssoData'
      example:
        type: loginInfo
        accessToken:
          id: RSP1npB7wZ4
          scopeId: AQ
          createdOn: '2019-11-15T14:43:27.547Z'
          createdBy: UlM9TGpJJ-g
          modifiedOn: '2019-11-15T14:43:27.547Z'
          modifiedBy: UlM9TGpJJ-g
          optlock: 1
          tokenId: eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL3d3dy5lY2xpcHNlLm9yZy9rYXB1YSIsImlhdCI6MTU3MzgyOTAwNywiZXhwIjoxNTczODMwODA3LCJzdWIiOiJVbE05VEdwSkotZyIsInNJZCI6IkFRIn0.LgVFKAl1Ftd3g81MhtUglee5JjCqd-gGjilj1UAkDbKs4Xwgo1j9V-CBVPF4aop3r0x80U9YaVthYoPEikG2v4QaRHl7UGeikWOHk4g0lpeFCZvS_Kcag6VgbfYKKXd2C2ivtQE3enjZIUEz2UTEXz3KrcizuvgO4SP_PEz5hGkjqfbV2l1IM--_E8LQRBQoD7ixpGajaUlcrNlLsJcNgy8hRgyNp_Bqbyosd4oBttC4oDIyVA9Wmgq8aXUwFl7SZ42Kd4RIUUlMg-aAIAzWXVMQ2kCY1jYy7eNUmLszWdmPjMZsKbFcB5asXXYiHvZ_zy0x9AHFRnFte721ESjG3NLlvx8UKOWLFBkmlbvgPLd5fhlzTzim57ddpTjJpRsTM123VSwKL6Ul3ZZKiADrBVi4By-C4BhIkS9hVfa-HzfWlQKUOJvpa7PuUuRT1XzxxSTwIjgE4XuNdxHRqJpJPg0XtAuN67KXhmXjeQUaDi05GvpV3VyhtO6_GjjoLRd934N2hBdgS6FLIYkxBVMNSyqzjg9QO_A6Yzul5JK8T6H-f7ZhlYsx3trkWw0I9jetQguPveChFY0xbeTHSW0PwyNpyXKBzIUQhwCH2zoI9LxUy7TV7yn5wN3IW5MocnOXtKG49BTIbslT4eccoTWhtFQafGu8OF0TN-QyMf0eGTQ
          userId: UlM9TGpJJ-g
          expiresOn: '2019-11-15T15:13:27.506Z'
          refreshToken: e8a53e18-0c6b-4f3c-9929-409069a9c66e
          refreshExpiresOn: '2019-11-15T19:43:27.506Z'
        accessPermissions:
          - id: Jfzafs5eUuw
            scopeId: AQ
            createdOn: '2019-11-15T14:43:11.451Z'
            createdBy: AQ
            accessInfoId: IKfvOdNER6M
            permission:
              domain: datastore
              action: read
              targetScopeId: AQ
              forwardable: false
        rolePermissions:
          - id: a716DxmV9TI
            scopeId: AQ
            createdOn: '2019-11-15T14:42:28.859Z'
            createdBy: AQ
            roleId: OgkB8tR0kF4
            permission:
              domain: device
              action: read
              targetScopeId: AQ
              forwardable: false
          - id: O0X0yIQo6NU
            scopeId: AQ
            createdOn: '2019-11-15T14:42:04.153Z'
            createdBy: AQ
            roleId: EUkieLf-Y8M
            permission:
              domain: user
              targetScopeId: AQ
              forwardable: false
        groupPermissions:
          - id: Jfzafs5eUuw
            scopeId: AQ
            createdOn: '2019-11-15T14:43:11.451Z'
            createdBy: AQ
            groupId: O0X0yIQo6NU
            permission:
              domain: datastore
              action: read
              targetScopeId: AQ
              forwardable: false
        groupRolePermissions:
          - id: a716DxmV9TI
            scopeId: AQ
            createdOn: '2019-11-15T14:42:28.859Z'
            createdBy: AQ
            roleId: OgkB8tR0kF4
            permission:
              domain: device
              action: write
              targetScopeId: AQ
              forwardable: false
          - id: O0X0yIQo6NU
            scopeId: AQ
            createdOn: '2019-11-15T14:42:04.153Z'
            createdBy: AQ
            roleId: EUkieLf-Y8M
            permission:
              domain: job
              targetScopeId: AQ
              forwardable: false
#        ssoData:
#          accountSupportsBrokering: true
#          accountSupportsDirectLogin: true
#          brokeringApiConnectionIssues: false
#          uriSuffixDirectLogin: '?accountid=my-account-name'
#          companyDomainNames:
#            - 'company.com'
#            - 'company.org'
#            - 'anothercompanydomain.net'
    usernamePasswordCredentials:
      allOf:
      - type: object
        properties:
          user:
            $ref: '#/components/schemas/username'
          password:
            $ref: '#/components/schemas/password'
          authenticationCode:
            $ref: '#/components/schemas/authenticationCode'
          trustKey:
            $ref: '#/components/schemas/trustKey'
          trustMe:
            type: boolean
            description: Whether to generate a TrustKey or not.
    jwtCredentials:
      type: object
      properties:
        accessToken:
          type: string
          pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
          description: The OpenID Connect <a href="https://auth0.com/blog/id-token-access-token-what-is-the-difference/#What-Is-an-Access-Token">accessToken</a>
        idToken:
          type: string
          pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
          description: The OpenID Connect <a href="https://auth0.com/blog/id-token-access-token-what-is-the-difference/#What-Is-an-ID-Token">idToken</a>.
      example:
        accessToken: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJrOUlYUlRMSm9jRlp6UzMycktnUHB2Ym9LYkJWMFNoUkNLdWxUMlBPWlRZIn0.eyJleHAiOjE3NDc5OTQ4NjEsImlhdCI6MTc0Nzk5NDU2MSwiYXV0aF90aW1lIjoxNzQ3OTk0MzA0LCJqdGkiOiI4ZTc3ZTdlNy1iZjgzLTRiMzctODQ2OC0yYTI3ZTA0YTVhMjciLCJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjY1OjkwOTAvcmVhbG1zL2VjIiwiYXVkIjpbImNvbnNvbGUiLCJhY2NvdW50Il0sInN1YiI6IjY2M2MwOGQ0LWI3Y2UtNDE5Mi1hYzU2LWMzMjU2ZjAwZDk0OCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNvbnNvbGUiLCJzZXNzaW9uX3N0YXRlIjoiMWNiYzY4NTItMDVjMy00NmZhLTgyNjQtMWYwN2U1NTIyYTgyIiwiYWNyIjoiMCIsImFsbG93ZWQtb3JpZ2lucyI6WyJodHRwOi8vbG9jYWxob3N0OjgwODMiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwiZGVmYXVsdC1yb2xlcy1lYyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInNpZCI6IjFjYmM2ODUyLTA1YzMtNDZmYS04MjY0LTFmMDdlNTUyMmE4MiIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoic3NvLXVzZXIifQ.cTqJbz4U3gBUiB1FE0N02tR6SzaeaJo3LmpNz77e1IfJ8w5A5FMxrOJ45oggmvE5LdknEmDLo8ZEbFV2Yop_AzRu_F7gErTD_yE6UdpRcWTN4W_pc4-oxSVS7jxZSEXfSntGl4lKcV9sEe3tcd6r5rwQM34nkQQBhQ3yklGqngCARlzQXnKeZbBR4Zegv7CeJXweiiwNXewcrv2LltQVxBi-x5nsy6CmETuZzaes5j4TqjCKxiYuv2l4Gd6d9JMA1Bg_1-jMb5fF_YQQFNfk_BsOAH1eILH3n6agC5D1wRg3jaYHhXrFZyP8_jFcxHf2VQWCkg1o8bO6OzfsAHXuVQ
        idToken: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJrOUlYUlRMSm9jRlp6UzMycktnUHB2Ym9LYkJWMFNoUkNLdWxUMlBPWlRZIn0.eyJleHAiOjE3NDc5OTQ4NjEsImlhdCI6MTc0Nzk5NDU2MSwiYXV0aF90aW1lIjoxNzQ3OTk0MzA0LCJqdGkiOiI1MDAxZTM5Ny1hMWQyLTRmYWMtOTU1Zi00MWQ3MDUyZGQ5YWIiLCJpc3MiOiJodHRwOi8vMTkyLjE2OC4xLjY1OjkwOTAvcmVhbG1zL2VjIiwiYXVkIjoiY29uc29sZSIsInN1YiI6IjY2M2MwOGQ0LWI3Y2UtNDE5Mi1hYzU2LWMzMjU2ZjAwZDk0OCIsInR5cCI6IklEIiwiYXpwIjoiY29uc29sZSIsInNlc3Npb25fc3RhdGUiOiIxY2JjNjg1Mi0wNWMzLTQ2ZmEtODI2NC0xZjA3ZTU1MjJhODIiLCJhdF9oYXNoIjoiQWlEeERwWmtlbjhRMk1oUEpTT2VydyIsImFjciI6IjAiLCJzaWQiOiIxY2JjNjg1Mi0wNWMzLTQ2ZmEtODI2NC0xZjA3ZTU1MjJhODIiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInByZWZlcnJlZF91c2VybmFtZSI6InNzby11c2VyIn0.RuC8AUvRr2eq7I1_NjowQeqSQsCy2wV6nz9kBLdDPXJFl0bNngu-tKYCuwAUaB-kAnfKYpJPDQQwHj_EXhNaXEXJBhpawDmRFBAx1yVcHe7ttLyWpjyc0btrI0AkzyrudFFolhF2briQqnlmqZma20eaxdpzG6vlb-dQZKgk5MM0Up7Ucb5oTp1M5ou2c0PWouF4z_g-191EyzwvoMsU4WGCC_mAIEs0J3aPnLwLrfVzXO1Sb86WTddnxlxdbp5nL2fbqAliHF6eneM5zyC2gecN-O5Pz7xkhIXo9L-nD6mVwmCgEdJXFEzvTZl1SNN1UWbxwnU37mLgXkD8WXOWpg
    username:
      type: string
      description: the username of the user
      pattern: '^[a-zA-Z0-9\_\-]{3,}$'
    password:
      type: string
      description: the password of the user
      pattern: '^.*(?=.{12,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!\"\#$%&''()*+,\-./:;<=>?@\[\]\\^_`{|}~]).*$'
    authenticationCode:
      type: string
      description: The MFA authentication code
      pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
    trustKey:
      type: string
      description: A long-lived key to be used within an authentication with MFA from a trusted machine
      pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
    jwt:
      type: string
      pattern: '^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$'
