services:
  db:
    image: kapua/kapua-sql-mysql:${IMAGE_VERSION}
    ports:
      - "8181:8181"
    environment:
      - MYSQL_ROOT_PASSWORD=KeepCalm123
      - MYSQL_DATABASE=kapuadb
      - MYSQL_USER=kapua
      - MYSQL_PASSWORD=kapua
      - CONNECTION_MAX
      - PACKET_ALLOWED_MAX
    command: --lower-case-table-names=1
