###############################################################################
# Copyright (c) 2018, 2022 Eurotech and/or its affiliates and others
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# Contributors:
#     Eurotech - initial API and implementation
#
###############################################################################
FROM mariadb:10.11.10

COPY maven /

# Assigning permission to write to mysql to allow write custom configurations
RUN chown -R mysql:0 /etc/mysql/conf.d && \
    chmod -R g=u /etc/mysql/conf.d

ENTRYPOINT ["/entrypoint-mariadb.sh"]